RazorPagesGeneral/Pages/Employees/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesLessons.Models;
using RazorPagesLessons.Services;

namespace RazorPagesGeneral.Pages.Employees
{
    public class DetailsModel : PageModel
    {
        private readonly IEmployeeRepository _employeeRepository;

        public DetailsModel(IEmployeeRepository employeeRepository)
        {
            _employeeRepository = employeeRepository;
        }

        public Language Employee { get; private set; }

        public IActionResult OnGet(int id)
        {
            Employee = _employeeRepository.GetEmployee(id);

            // Lesson 6
            if (Employee == null)
                return RedirectToPage("/NotFound");

            return Page();
        }
    }
}

RazorPagesGeneral/Pages/Employees/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesLessons.Services;
using RazorPagesLessons.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;

namespace RazorPagesGeneral.Pages.Employees
{
    public class EditModel : PageModel
    {
        private readonly IEmployeeRepository _employeeRepository;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public EditModel(IEmployeeRepository employeeRepository, IWebHostEnvironment webHostEnvironment)
        {
            _employeeRepository = employeeRepository;
            _webHostEnvironment = webHostEnvironment;
        }

        public Language Employee { get; set; }
        [BindProperty]
        public IFormFile Photo { get; set; }

        [BindProperty]
        public bool Notify { get; set; }
        public string Massage { get; set; }


        public IActionResult OnGet(int id)
        {
            Employee = _employeeRepository.GetEmployee(id);

            if (Employee == null)
                return RedirectToPage("/NotFound");
            return Page();
        }

        public IActionResult OnPost(Language employee)
        {
            if(Photo != null)
            {
                if(employee.PhotoPath != null)
                {
                    string filePath = Path.Combine(_webHostEnvironment.WebRootPath, "images", employee.PhotoPath);
                    System.IO.File.Delete(filePath);
                }

                employee.PhotoPath = ProcessUploadedFile();
            }

            Employee = _employeeRepository.Update(employee);

            TempData["SeccessMessage"] = $"Update{Employee.Name} successful!";

            return RedirectToPage("Employees");
        }


        public void OnPostUpdateNotificationPreferences(int id)
        {
            if (Notify)
                Massage = "Thank you for turning on notifications";
            else
                Massage = "You have turned off email notifications";

            Employee = _employeeRepository.GetEmployee(id);

        }


        private string ProcessUploadedFile()
        {
            string uniqueFileName = null;

            if(Photo != null)
            {
                string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_" + Photo.FileName;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);

                using(var fs = new FileStream(filePath, FileMode.Create))
                {
                    Photo.CopyTo(fs);
                }
            }
            return uniqueFileName;
        }

    }
}

RazorPagesGeneral/Pages/Employees/Employees.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using RazorPagesLessons.Services;
using RazorPagesLessons.Models;

namespace RazorPagesGeneral.Pages.Employees
{
    public class EmployeesModel : PageModel
    {

        private readonly IEmployeeRepository _db;

        public EmployeesModel(IEmployeeRepository db)
        {
            _db = db;
        }

        public IEnumerable<Language> Employees { get; set; }

        public void OnGet()
        {
            Employees = _db.GetAllEmployees();
        }
    }
}

RazorPagesGeneral/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPagesGeneral.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public class ErrorModel : PageModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

RazorPagesGeneral/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPagesGeneral.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        public string Message { get; set; }

        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            Message = $"Welcome to our first Razor Page Application\nThe time now is:{DateTime.Now.ToLongTimeString()}";
        }
    }
}

RazorPagesGeneral/Pages/NotFound.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace RazorPagesGeneral.Pages
{
    public class NotFoundModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

RazorPagesGeneral/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RazorPagesGeneral.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

RazorPagesGeneral/Pages/Employees/Details.cshtml
@page "{id}"
@model RazorPagesGeneral.Pages.Employees.DetailsModel
@{
    ViewData["Title"] = "Employee Details";
    var photoPath = $"/images/{Model.Employee.PhotoPath ?? "noimage.png"}";

}

<div class="row justify-content-center m-3">
    <div class="col col-lg-8">
        <div class="card cardBoxShadow">

            <div class="card-header cardHeaderStyle text-center">
                <h1>@Model.Employee.Name</h1>
            </div>

            <div class="card-body cardBoxShadow text-center">
                <div class="row">
                    <div class="col col-lg-9">
                        <h4 class="cardTextLeftFloating ">Employee ID: @Model.Employee.Id</h4><hr />
                        <h4 class="cardTextLeftFloating ">Email: @Model.Employee.Email</h4><hr />
                        <h4 class="cardTextLeftFloating ">Department: <span class="text-danger font-weight-bold">@Model.Employee.Department</span> </h4><hr />
                    </div>
                    <div class="col col-lg-3">
                        <div style="border-right: 1px solid rgba(0, 0, 0, .1);">
                            <img class="card-img-top imageThumbnail border border-primary " style="background-color: #dle7ff;" src ="@photoPath" asp-append-version="true" />
                        </div>
                    </div>

                </div>
            </div>

            <div class="row">
                <div class="col ">
                    <div class="card-footer text-center" style="background-color: rgba(0,0,0,0.25);">
                        <a asp-page="Employees" class="btn btn-success buttonShadow">Back</a>
                        <a href="#" class="btn btn-primary buttonShadow">Edit</a>
                        <a href="#" class="btn btn-danger buttonShadow">Delete</a>

                    </div>
                </div>
            </div>

        </div>
    </div>
</div>

RazorPagesGeneral/Pages/Employees/Edit.cshtml
@page "{id}/{handler?}"
@model RazorPagesGeneral.Pages.Employees.EditModel
@{
    ViewData["Title"] = "Edit";
    var photoPath = $"/images/{Model.Employee.PhotoPath ?? "noimage.png"}";
}

<form method="post" asp-page-handler="UpdateNotificationPreferences">
    <div class="row text-center notifyBlock">
        <div class="col form-check">
            <h1>Notification Preference</h1>
            <input asp-for="Notify" class="form-check-input" />
            <label asp-for="Notify" class="form-check-label">
                Receive email notification when my details change
            </label><br />

            <button type="submit" class="btn-primary text-center">Update Notification Preference</button>

            @if(!string.IsNullOrWhiteSpace(Model.Massage))
            {
                <div class="alert alert-success">
                    <p class="p-3 mt-2">@Model.Massage</p>
                </div>
            }

        </div>
    </div>
</form>
<hr />

<!--Создаём форму редактирования-->
<form method="post" asp-page-handler="OnPost" class="mt-3" enctype="multipart/form-data">
    <!--Создаём скрытое поле для параметра ID-->
    <input type="hidden" asp-for="Employee.Id" />
    <input type="hidden" asp-for="Employee.PhotoPath" />

    <!--Добавляем поля редактирования-->
    <div class="row justify-content-center m-3">
        <div class="col col-lg-8">
            <div class="card cardBoxShadow">
                <div class="card-header cardHeaderStyle text-center">
                    <!--Добавляем поле редактирования имени-->
                    <div class="form-group row">
                        <label asp-for="Employee.Email" class="col col-lg-4 col-form-label text-right">Edit E-mail:</label>
                        <div class="col col-lg-6">
                            <input asp-for="Employee.Email" class="form-control" placeholder="@Model.Employee.Email" />
                            <!--Добавляем сообщение валидации формы-->
                            <span asp-validation-for="Employee.Email" class="text-danger"></span>
                        </div>
                    </div>

                </div>
                <div class="card-body cardBodyStyle text-center">
                    <div class="row">
                        <div class="col col-lg-9">
                            <h4 class="cardTextLeftFloating">Employee ID: @Model.Employee.Id</h4><hr />

                            <!--Добавляем поле редактирования e-mail-->
                            <div class="form-group row">
                                <label asp-for="Employee.Email" class="col col-lg-4 col-form-label text-right">Edit E-mail:</label>
                                <div class="col-12 col-lg-6">
                                    <input asp-for="Employee.Email" class="form-control mr-2" placeholder="@Model.Employee.Email" />
                                    <!--Добавляем сообщение валидации формы-->
                                    <span asp-validation-for="Employee.Email" class="text-danger"></span>
                                </div>
                            </div>
                            <hr />
                            <!--Добавляем поле редактирования департамента-->
                            <div class="form-group row">
                                <label asp-for="Employee.Department" class="col col-lg-4 col-form-label text-right">Edit Department:</label>
                                <div class="col-12 col-lg-6">
                                    <!--Создаём выпадающий список с департаментами-->
                                    <!--Необходимо подключить класс локально или глобально-->
                                    <select asp-for="Employee.Department" class="custom-select mr-2" asp-items="Html.GetEnumSelectList<Dept>()">
                                        <!--Добавляем начальный элемент выпадающего списка-->
                                        <option value="">Please Select</option>
                                    </select>
                                    <span asp-validation-for="Employee.Department" class="text-danger"></span>
                                </div>
                            </div>
                            <hr />
                        </div>

                        <div class="col col-lg-3">
                            <div>

                                <img class="card-img-top img-thumbnail border border-primary" src="@photoPath" asp-append-version="true" />

                                <div class="custom-file">
                                    <input asp-for="Photo" class="custom-file-input form-control" />
                                    <label class="custom-file-label text-left">Click here</label>
                                </div>

                            </div>
                        </div>

                    </div>
                    <div class="row">
                        <div class="col">
                            <div class="card-footer text-center" style="background-color: rgba(0, 0, 0, 0.25);">
                                <button type="submit" class="btn btn-success buttonShadow">Update</button>
                                <a asp-page="index" class="btn btn-danger buttonShadow">Cancel</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    @section Scripts{
        <script>
            $(document).ready(function () {
                $('.custom-file-input').on("change", function () {
                    var fileName = $(this).val().split("\\").pop();
                    $(this).next('.custom-file-label').html(fileName);
                });
            });
        </script>

    }

</form>

RazorPagesGeneral/Pages/Employees/Employees.cshtml
@page
@model RazorPagesGeneral.Pages.Employees.EmployeesModel
@{
    ViewData["Title"] = "Employees";
}


@if(TempData["SeccessMessage"] != null)
{
<div class="alert alert-success text-center">
    @TempData["SeccessMessage"]
</div>
}

<h1>Employees</h1>

<div class="row">
    @foreach(var item in Model.Employees)
    {
        // формируем путь к фото
        var photoPath = $"/images/{item.PhotoPath ?? "noimage.png"}";
        <div class="col-12 col-sm-6 col-lg-4" >
            <div class="card-deck">
                <div class="card m-3 cardBoxShadow">
                    <div class="card-header text-center cardHeaderStyle">
                        <h3>@item.Name</h3>
                    </div>

                    <div class="text-center cardBodyStyle">
                        <img class="card-img-top imageThumbnail" src ="@photoPath" asp-append-version="true" />
                    </div>

                    <div class=" card-footer text-center">
                        <a asp-page="/Employees/Details" asp-route-Id="@item.Id" class="btn btn-success m-1 buttonShadow">View</a>
                        <a asp-page="/Employees/Edit" asp-route-Id="@item.Id" class="btn btn-primary m-1 buttonShadow">Edit</a>
                        <a href="#" class="btn btn-danger m-1 buttonShadow">Delete</a>

                    </div>

                </div>
            </div>
        </div>
    }
</div>

RazorPagesGeneral/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class = " row text-center p-3 mb-2 bg-secondary text-white">
    <div class="col">
        <h1> Welcome Привет 你好 </h1>
        <h2>for the best foreign language course in the world</h2>
    </div>
</div>

<div class="row text-center p-3 mb-2 bg-secondary text-white">
    <div class="col">
        <img src="~/images/Planeta.jpg" class="w-50 img-fluid img-thumbnail" alt=" From Dmitrii course " />
    </div>
</div>

RazorPagesGeneral/Pages/NotFound.cshtml
@page
@model RazorPagesGeneral.Pages.NotFoundModel
@{
    ViewData["Title"] = "Not Found";

}

<div class="row">
    <div class="col text-center">
        <img src="~/images/NotFound.png" alt="Page Not Found" />
    </div>
</div>

<div class="row">
    <div class="col text-center ">
        <h1>The resource you are looking for cannot be found!</h1>
        <a asp-page="/Employees/Employees" class="btn btn-primary">Click here to get back to Employees list page</a>
    </div>
</div>

RazorPagesGeneral/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RazorPagesGeneral</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar fixed-top  navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3 menuBg">
            <div class="container">
                <a class="navbar-brand text-white" asp-area="" asp-page="/Index">
                    <img src="~/images/LessonsCoreLogo.png" alt="Demonick Lessons" />
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-page="/Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-page="/Employees/Employees">Employees</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-page="/Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container containerBordered">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="footer text-muted">
        <div class="container border">
            &copy; 2021 - DEMONICK LESSONS - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>